# This file was generated by the `rails generate rspec:install` command.
# Keep this file lightweight. Rails is loaded from rails_helper.rb when needed.

require "shoulda/matchers"

RSpec.configure do |config|
  # --- Expectations ----------------------------------------------------------
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # --- Mocks ----------------------------------------------------------------
  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end

  # --- Shared Context Behavior ----------------------------------------------
  config.shared_context_metadata_behavior = :apply_to_host_groups

  # --- Quality-of-life defaults ---------------------------------------------
  # Run only focused examples when present: `fit`, `fdescribe`, `fcontext` or `:focus`
  config.filter_run_when_matching :focus

  # Remember example statuses to support `--only-failures` / `--next-failure`
  config.example_status_persistence_file_path = "spec/examples.txt"

  # Use doc formatter when running a single file for nicer output
  if config.files_to_run.one?
    config.default_formatter = "doc"
  end

  # Show 5 slowest examples/groups at the end
  config.profile_examples = 5

  # Randomize to surface order dependencies
  config.order = :random
  Kernel.srand config.seed

  # If you prefer strict non-monkey-patched syntax, uncomment:
  # config.disable_monkey_patching!
end
